"""Save remaining pages 39, 40, 42 with full feature lists from MCP responses."""
import json, os
os.makedirs('goal/package_2_dzfinal', exist_ok=True)

# Page 39 full features (need all 100 - currently 33)
# Features 34-100 from the page 39 MCP response
page39_more = [
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_3m_to_6m_xd_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来3月到6月小额贷款公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_3m_to_6m_xd_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_xd_payment_mean","featureName":"与最近一份报文相比，人行未来6月小额贷款公司贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_6m_xd_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_to_24m_tot_payment_mean","featureName":"与最近一份报文相比，人行未来12月到24月所有贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_12m_to_24m_tot_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_to_36m_xj_payment_mean","featureName":"与最近一份报文相比，人行未来24月到36月消费金融公司贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_24m_to_36m_xj_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_to_12m_biz_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来9月到12月个人经营性贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_9m_to_12m_biz_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_bank_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来24月商业银行贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_24m_bank_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_3m_to_6m_bank_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来3月到6月商业银行贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_3m_to_6m_bank_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_to_9m_edu_payment_mean","featureName":"与最近一份报文相比，人行未来6月到9月个人助学贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_6m_to_9m_edu_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_to_36m_biz_payment_mean","featureName":"与最近一份报文相比，人行未来24月到36月个人经营性贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_24m_to_36m_biz_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_biz_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来9月个人经营性贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_9m_biz_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_to_60m_rd_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来48月到60月融资担保公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_48m_to_60m_rd_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_to_3m_non_xxhb_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来近1月到3月非先息后本贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_1m_to_3m_non_xxhb_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_to_48m_tot_payment_mean","featureName":"与最近一份报文相比，人行未来36月到48月所有贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_to_48m_tot_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_edu_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来6月个人助学贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_6m_edu_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_total_future_3m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来3月所有应还汇总增加量","featureColumnName":"recent_dif_total_future_3m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_to_24m_car_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来12月到24月个人汽车消费贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_12m_to_24m_car_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_rd_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来48月融资担保公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_48m_rd_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_non_xxhb_payment_min_act_pay","featureName":"与最近一份报文相比，人行未来1月先息后本贷款应还最小值增加量","featureColumnName":"recent_dif_loan_future_1m_non_xxhb_payment_min_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_tot_payment_mean","featureName":"与最近一份报文相比，人行未来36月所有贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_tot_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_60m_non_xxhb_payment_sum","featureName":"与最近一份报文相比，人行未来近60月非先息后本贷款应还汇总增加量","featureColumnName":"recent_dif_loan_future_60m_non_xxhb_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_xxhb_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来9月先息后本贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_9m_xxhb_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_car_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来12月个人汽车消费贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_12m_car_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_3m_xj_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来3月消费金融公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_3m_xj_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_xd_payment_mean","featureName":"与最近一份报文相比，人行未来12月小额贷款公司贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_12m_xd_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_xxhb_payment_mean","featureName":"与最近一份报文相比，人行未来24月先息后本贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_24m_xxhb_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_to_60m_xxhb_payment_sum","featureName":"与最近一份报文相比，人行未来48月到60月先息后本贷款应还汇总增加量","featureColumnName":"recent_dif_loan_future_48m_to_60m_xxhb_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_to_12m_mort_fund_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来9月到12月个人住房公积金贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_9m_to_12m_mort_fund_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_farm_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来24月农户贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_24m_farm_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_card_future_24m_to_36m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来24月到36月贷记卡应还汇总增加量","featureColumnName":"recent_dif_card_future_24m_to_36m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_3m_to_6m_farm_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来3月到6月农户贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_3m_to_6m_farm_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_to_9m_oth_con_payment_mean","featureName":"与最近一份报文相比，人行未来6月到9月其他机构贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_6m_to_9m_oth_con_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_to_36m_mort_fund_payment_mean","featureName":"与最近一份报文相比，人行未来24月到36月个人住房公积金贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_24m_to_36m_mort_fund_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_mort_fund_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来9月个人住房公积金贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_9m_mort_fund_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_to_3m_xd_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来近1月到3月小额贷款公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_1m_to_3m_xd_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_xd_payment_mean","featureName":"与最近一份报文相比，人行未来36月小额贷款公司贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_xd_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_3m_farm_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来3月农户贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_3m_farm_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_oth_con_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来6月其他机构贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_6m_oth_con_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_total_future_60m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来所有应还汇总增加量","featureColumnName":"recent_dif_total_future_60m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_to_24m_non_xxhb_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来12月到24月非先息后本贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_12m_to_24m_non_xxhb_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_to_60m_car_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来48月到60月个人汽车消费贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_48m_to_60m_car_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_to_3m_bank_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来近1月到3月商业银行贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_1m_to_3m_bank_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_to_48m_edu_payment_mean","featureName":"与最近一份报文相比，人行未来36月到48月个人助学贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_to_48m_edu_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_60m_xd_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来小额贷款公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_60m_xd_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_total_future_1m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来1月所有应还汇总增加量","featureColumnName":"recent_dif_total_future_1m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_non_xxhb_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来12月非先息后本贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_12m_non_xxhb_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_car_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来48月个人汽车消费贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_48m_car_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_bank_payment_sum_act_pay","featureName":"与最近一份报文相比，人行未来1月商业银行贷款应还汇总actpay增加量","featureColumnName":"recent_dif_loan_future_1m_bank_payment_sum_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_edu_payment_mean","featureName":"与最近一份报文相比，人行未来36月个人助学贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_edu_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_60m_bank_payment_sum","featureName":"与最近一份报文相比，人行未来商业银行贷款应还汇总增加量","featureColumnName":"recent_dif_loan_future_60m_bank_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_to_12m_tot_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来9月到12月所有贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_9m_to_12m_tot_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_rd_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来24月融资担保公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_24m_rd_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_card_future_6m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来6月贷记卡应还汇总增加量","featureColumnName":"recent_dif_card_future_6m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_3m_to_6m_rd_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来3月到6月融资担保公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_3m_to_6m_rd_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_to_9m_xj_payment_mean","featureName":"与最近一份报文相比，人行未来6月到9月消费金融公司贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_6m_to_9m_xj_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_to_36m_tot_payment_mean","featureName":"与最近一份报文相比，人行未来24月到36月所有贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_24m_to_36m_tot_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_tot_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来9月所有贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_9m_tot_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_xj_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来1月消费金融公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_1m_xj_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_3m_biz_payment_mean","featureName":"与最近一份报文相比，人行未来3月个人经营性贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_3m_biz_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_3m_rd_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来3月融资担保公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_3m_rd_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_to_9m_biz_payment_mean","featureName":"与最近一份报文相比，人行未来6月到9月个人经营性贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_6m_to_9m_biz_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_total_future_9m_to_12m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来9月到12月所有应还汇总增加量","featureColumnName":"recent_dif_total_future_9m_to_12m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_to_60m_non_xxhb_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来48月到60月非先息后本贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_48m_to_60m_non_xxhb_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_to_3m_farm_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来近1月到3月农户贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_1m_to_3m_farm_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_to_48m_oth_con_payment_mean","featureName":"与最近一份报文相比，人行未来36月到48月其他机构贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_to_48m_oth_con_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_biz_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来6月个人经营性贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_6m_biz_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_total_future_36m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来36月所有应还汇总增加量","featureColumnName":"recent_dif_total_future_36m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_to_24m_bank_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来12月到24月商业银行贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_12m_to_24m_bank_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
]

# Read existing page 39, append more features, save
with open('goal/package_2_dzfinal/page_0039.json') as f:
    p39 = json.load(f)
p39['features'].extend(page39_more)
p39['featureCount'] = len(p39['features'])
with open('goal/package_2_dzfinal/page_0039.json', 'w') as f:
    json.dump(p39, f, ensure_ascii=False)
print(f"Page 39: now {len(p39['features'])} features (added {len(page39_more)})")

# Page 40 - need to re-save with more features
# Read existing and add more from the MCP response
page40_more = [
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_to_3m_car_payment_sum_act_pay","featureName":"与最近一份报文相比，人行未来近1月到3月个人汽车消费贷款应还汇总actpay增加量","featureColumnName":"recent_dif_loan_future_1m_to_3m_car_payment_sum_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_to_60m_bank_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来48月到60月商业银行贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_48m_to_60m_bank_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_mort_fund_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来6月个人住房公积金贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_6m_mort_fund_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_to_12m_non_xxhb_payment_sum_act_pay","featureName":"与最近一份报文相比，人行未来9月到12月非先息后本贷款应还汇总actpay增加量","featureColumnName":"recent_dif_loan_future_9m_to_12m_non_xxhb_payment_sum_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_xxhb_payment_mean","featureName":"与最近一份报文相比，人行未来24月先息后本贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_24m_xxhb_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_edu_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来1月个人助学贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_1m_edu_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_rd_payment_sum_act_pay","featureName":"与最近一份报文相比，人行未来12月融资担保公司贷款应还汇总actpay增加量","featureColumnName":"recent_dif_loan_future_12m_rd_payment_sum_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_bank_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来48月商业银行贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_48m_bank_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_60m_rd_payment_sum","featureName":"与最近一份报文相比，人行未来融资担保公司贷款应还汇总增加量","featureColumnName":"recent_dif_loan_future_60m_rd_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_non_xxhb_payment_sum_act_pay","featureName":"与最近一份报文相比，人行未来9月非先息后本贷款应还汇总actpay增加量","featureColumnName":"recent_dif_loan_future_9m_non_xxhb_payment_sum_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
]

with open('goal/package_2_dzfinal/page_0040.json') as f:
    p40 = json.load(f)
p40['features'].extend(page40_more)
p40['featureCount'] = len(p40['features'])
with open('goal/package_2_dzfinal/page_0040.json', 'w') as f:
    json.dump(p40, f, ensure_ascii=False)
print(f"Page 40: now {len(p40['features'])} features (added {len(page40_more)})")

# Page 42 - save new with features from the MCP response (first batch)
page42_features = [
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_03_feature_di.recent_dif_qry_is_recent_600d_qry_to_now_min_div_wave","featureName":"与最近一份报文相比，人行近600天查询最小值趋势-相除增加量","featureColumnName":"recent_dif_qry_is_recent_600d_qry_to_now_min_div_wave","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_03_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表03_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_03_feature_di.recent_div_qry_is_recent_150d_qry_to_now_count_div_wave","featureName":"与最近一份报文相比，人行近150天查询次数趋势-相除增加占比","featureColumnName":"recent_div_qry_is_recent_150d_qry_to_now_count_div_wave","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_03_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表03_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
{"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_03_feature_di.recent_dif_loan_card_is_630d_cur_ovd_amt_y_count","featureName":"与最近一份报文相比，人行贷记卡近630天当前逾期账户数增加量","featureColumnName":"recent_dif_loan_card_is_630d_cur_ovd_amt_y_count","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_03_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表03_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
]

page42 = {"page":42,"total":6619,"featureCount":len(page42_features),"features":page42_features}
with open('goal/package_2_dzfinal/page_0042.json','w') as f:
    json.dump(page42, f, ensure_ascii=False)
print(f"Page 42: {len(page42_features)} features saved (partial)")

print("\nSUMMARY:")
for pg in [38,39,40,41,42]:
    fn = f'goal/package_2_dzfinal/page_{pg:04d}.json'
    with open(fn) as f:
        d = json.load(f)
    print(f"  Page {pg}: {len(d['features'])} features, {os.path.getsize(fn)} bytes")
