import json, os
os.makedirs('goal/package_2_dzfinal', exist_ok=True)

features = [
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_rd_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来1月融资担保公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_1m_rd_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_to_48m_biz_payment_mean","featureName":"与最近一份报文相比，人行未来36月到48月个人经营性贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_to_48m_biz_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_60m_rd_payment_sum","featureName":"与最近一份报文相比，人行未来融资担保公司贷款应还汇总增加量","featureColumnName":"recent_dif_loan_future_60m_rd_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_total_future_12m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来12月所有应还汇总增加量","featureColumnName":"recent_dif_total_future_12m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_farm_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来12月农户贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_12m_farm_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_bank_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来48月商业银行贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_48m_bank_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_xxhb_payment_mean","featureName":"与最近一份报文相比，人行未来12月先息后本贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_12m_xxhb_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_biz_payment_mean","featureName":"与最近一份报文相比，人行未来36月个人经营性贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_biz_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_xj_payment_sum","featureName":"与最近一份报文相比，人行未来48月消费金融公司贷款应还汇总增加量","featureColumnName":"recent_dif_loan_future_48m_xj_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_to_12m_oth_con_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来9月到12月其他机构贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_9m_to_12m_oth_con_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_non_xxhb_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来24月非先息后本贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_24m_non_xxhb_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_card_future_3m_to_6m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来3月到6月贷记卡应还汇总增加量","featureColumnName":"recent_dif_card_future_3m_to_6m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_3m_to_6m_non_xxhb_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来3月到6月非先息后本贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_3m_to_6m_non_xxhb_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_to_9m_tot_payment_mean","featureName":"与最近一份报文相比，人行未来6月到9月所有贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_6m_to_9m_tot_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_24m_to_36m_oth_con_payment_mean","featureName":"与最近一份报文相比，人行未来24月到36月其他机构贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_24m_to_36m_oth_con_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_oth_con_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来9月其他机构贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_9m_oth_con_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_to_3m_xxhb_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来近1月到3月先息后本贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_1m_to_3m_xxhb_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_xxhb_payment_mean","featureName":"与最近一份报文相比，人行未来36月先息后本贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_xxhb_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_3m_non_xxhb_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来3月非先息后本贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_3m_non_xxhb_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_6m_tot_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来6月所有贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_6m_tot_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_total_future_6m_to_9m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来6月到9月所有应还汇总增加量","featureColumnName":"recent_dif_total_future_6m_to_9m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_to_60m_farm_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来48月到60月农户贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_48m_to_60m_farm_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_to_3m_car_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来近1月到3月个人汽车消费贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_1m_to_3m_car_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_to_48m_mort_fund_payment_mean","featureName":"与最近一份报文相比，人行未来36月到48月个人住房公积金贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_to_48m_mort_fund_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_60m_xxhb_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来近60月先息后本贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_60m_xxhb_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_total_future_24m_tot_payment_sum","featureName":"与最近一份报文相比，人行未来24月所有应还汇总增加量","featureColumnName":"recent_dif_total_future_24m_tot_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_12m_rd_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来12月融资担保公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_12m_rd_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_48m_farm_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来48月农户贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_48m_farm_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_1m_car_payment_sum_act_pay","featureName":"与最近一份报文相比，人行未来1月个人汽车消费贷款应还汇总actpay增加量","featureColumnName":"recent_dif_loan_future_1m_car_payment_sum_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_36m_mort_fund_payment_mean","featureName":"与最近一份报文相比，人行未来36月个人住房公积金贷款应还均值增加量","featureColumnName":"recent_dif_loan_future_36m_mort_fund_payment_mean","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_60m_car_payment_sum","featureName":"与最近一份报文相比，人行未来个人汽车消费贷款应还汇总增加量","featureColumnName":"recent_dif_loan_future_60m_car_payment_sum","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_future_9m_to_12m_xj_payment_mean_act_pay","featureName":"与最近一份报文相比，人行未来9月到12月消费金融公司贷款应还均值actpay增加量","featureColumnName":"recent_dif_loan_future_9m_to_12m_xj_payment_mean_act_pay","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
    {"featureCode":"ftr.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di.recent_dif_loan_balance_mean_non_xxhb_180d","featureName":"与最近一份报文相比，人行180天先息后本贷款余额均值增加量","featureColumnName":"recent_dif_loan_balance_mean_non_xxhb_180d","groupCode":"fg.off.usr.dwa_risk_dz_model_final_32rh_double_04_feature_di","groupName":"贷中人行特征衍生_双报文变量特征表04_人行报文维度","domainCode":"UID","includeTodayFlag":0,"timeRange":180},
]

page = {"page":39,"total":6619,"featureCount":len(features),"features":features}
with open('goal/package_2_dzfinal/page_0039.json','w') as f:
    json.dump(page, f, ensure_ascii=False)
print(f"OK page 39: {len(features)} features saved")
